title: The Rise of Protein Obsession
description: A DSC 80 data science project by Leo Wong
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
logo: /assets/protein-icon.svg
show_downloads: false
